### ISSUE TITLE
更新了什么内容？无线模式同时能控制几台设备？

### ISSUE THREAD

**Issue by fuxin-mail** [Gasolcloudteam/Scrcpy-scripts#1]
更新了什么内容？无线模式同时能控制几台设备？

**Comment by Gasolcloudteam** [comment]
> 更新了什么内容？无线模式同时能控制几台设备？

更新拉取了最新的 25 版本，之前是 24 版本，无线控制如果需要多台设备，可以多开几个配置无线投屏的脚本，输入对应被控设备 IP 即可控制。

**Comment by fuxin-mail** [comment]
谢谢
&nbsp;


俗客-白丁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月12日(星期五) 晚上10:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Gasolcloudteam/Scrcpy-scripts] 更新了什么内容？无线模式同时能控制几台设备？ (Issue #1)














  
更新了什么内容？无线模式同时能控制几台设备？
  
更新拉取了最新的 25 版本，之前是 24 版本，无线控制如果需要多台设备，可以多开几个配置无线投屏的脚本，输入对应被控设备 IP 即可控制。
